<?xml version="1.0"?>
<package format="3">
  <name>panda_move_it_dev</name>
  <version>0.1.0</version>
  <description>Standalone Panda + MoveIt demo node</description>
  <maintainer email="you@example.com">You</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
