<?xml version="1.0"?>
<package format="3">
  <name>moveit_resources_panda_description</name>
  <version>3.1.1</version>
  <description>Robot description (URDF/Xacro + meshes) for Franka Panda used in MoveIt resources.</description>

  <maintainer email="mike@picknik.ai">Mike Lautman</maintainer>
  <author email="mike@picknik.ai">Mike Lautman</author>
  <license>BSD</license>

  <url type="website">http://moveit.ros.org/</url>
  <url type="bugtracker">https://github.com/ros-planning/moveit_resources/issues</url>
  <url type="repository">https://github.com/ros-planning/moveit_resources</url>

  <!-- Python build tool -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Run deps (xacro is commonly used with these descriptions) -->
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
